### ISSUE TITLE
TODO: MVP items

### ISSUE THREAD

**Issue by rachelnicole** [rachelnicole/ricks-big-day#1]
Items that need to be completed in order to have a MVP for this ✨ game ✨. 

ACCOUNTABILITY OK. In order of importance from top to bottom

Coding Issues > 
- [x] platform sprites 6/1
- [x] animated sprites FOR INTERACTION 6/2
- [x] ^^^ based on key press while colliding with item. 6/2
- [x] ^^^ cause points to go up 6/2
- [x] ^^^ that have a cooldown before you can interact again 6/3
- [x] stage not confined to screen, create scrollable borders on Rick's movement 6/4 slash 6/5
- [ ] "cat nap" stage 
- [ ] "sleep" stage

Art to be done >
- [ ] more cat toys
- [ ] kitchen potentially
- [ ] more living room
- [ ] bedroom

GOAL IS TO HAVE MOST OF THESE DONE BY 6/7

**Comment by rachelnicole** [comment]
Platform sprites are completed. Have to split each sprite item up into pieces because tilesets don't support multiple collision directions or some garbage idk phaser's docs still are weird.

Interactivity is a lot of garbage code, which is just copying and pasting. Going to keep it to potentially just a few rooms so the code isn't super verbose but who cares this is for fun and not for someone to run a linter on. 😎

**Comment by rachelnicole** [comment]
ahhh all basic coding interactions are done and ready to be cloned to more interactive stages.
